[package]
name = "emeraldchicago/module-loader"
description = "A simple attribute-driven module loader for Roblox with with module relocation and parallel execution support. - fixed for argon"
version = "3.0.5"
license = "MIT"
authors = ["emeraldchicago"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
repository = "https://github.com/emeraldchicago/module-loader"
exclude = [
    "**",
]
include = [
    "default.project.json",
    "src",
    "src/**",
    "LICENSE",
    "wally.toml",
    "README.md",
    "rbxm",
    "rbxm/*.rbxmx",
]
